export interface BibleBook {
  id: string; // e.g. 'JHN'
  name: string; // e.g. 'João'
  abbrev: string; // e.g. 'Jo'
  testament: 'AT' | 'NT';
  chapters: number;
  usfm: string; // e.g. 'JHN'
}

export interface BibleVerse {
  book: string;
  bookId: string;
  chapter: number;
  verse: number | string;
  text: string;
  version?: string;
  theme?: string;
  lutheranNote?: string;
}

export interface BibleVersionOption {
  id: string;
  name: string;
  code: string;
  bibleComId: string;
  lang: string;
}

export const BIBLE_VERSIONS: BibleVersionOption[] = [
  { id: 'nvi', name: 'Nova Versão Internacional (NVI)', code: 'NVI', bibleComId: '129', lang: 'pt' },
  { id: 'ara', name: 'Almeida Revista e Atualizada (ARA)', code: 'ARA', bibleComId: '1608', lang: 'pt' },
  { id: 'arc', name: 'Almeida Revista e Corrigida (ARC)', code: 'ARC', bibleComId: '212', lang: 'pt' },
  { id: 'nvt', name: 'Nova Versão Transformadora (NVT)', code: 'NVT', bibleComId: '211', lang: 'pt' },
  { id: 'niv', name: 'New International Version (NIV)', code: 'NIV', bibleComId: '111', lang: 'en' },
];

export const BIBLE_BOOKS: BibleBook[] = [
  // Antigo Testamento (39 livros)
  { id: 'GEN', name: 'Gênesis', abbrev: 'Gn', testament: 'AT', chapters: 50, usfm: 'GEN' },
  { id: 'EXO', name: 'Êxodo', abbrev: 'Êx', testament: 'AT', chapters: 40, usfm: 'EXO' },
  { id: 'LEV', name: 'Levítico', abbrev: 'Lv', testament: 'AT', chapters: 27, usfm: 'LEV' },
  { id: 'NUM', name: 'Números', abbrev: 'Nm', testament: 'AT', chapters: 36, usfm: 'NUM' },
  { id: 'DEU', name: 'Deuteronômio', abbrev: 'Dt', testament: 'AT', chapters: 34, usfm: 'DEU' },
  { id: 'JOS', name: 'Josué', abbrev: 'Js', testament: 'AT', chapters: 24, usfm: 'JOS' },
  { id: 'JDG', name: 'Juízes', abbrev: 'Jz', testament: 'AT', chapters: 21, usfm: 'JDG' },
  { id: 'RUT', name: 'Rute', abbrev: 'Rt', testament: 'AT', chapters: 4, usfm: 'RUT' },
  { id: '1SA', name: '1 Samuel', abbrev: '1Sm', testament: 'AT', chapters: 31, usfm: '1SA' },
  { id: '2SA', name: '2 Samuel', abbrev: '2Sm', testament: 'AT', chapters: 24, usfm: '2SA' },
  { id: '1KI', name: '1 Reis', abbrev: '1Rs', testament: 'AT', chapters: 22, usfm: '1KI' },
  { id: '2KI', name: '2 Reis', abbrev: '2Rs', testament: 'AT', chapters: 25, usfm: '2KI' },
  { id: '1CH', name: '1 Crônicas', abbrev: '1Cr', testament: 'AT', chapters: 29, usfm: '1CH' },
  { id: '2CH', name: '2 Crônicas', abbrev: '2Cr', testament: 'AT', chapters: 36, usfm: '2CH' },
  { id: 'EZR', name: 'Esdras', abbrev: 'Ed', testament: 'AT', chapters: 10, usfm: 'EZR' },
  { id: 'NEH', name: 'Neemias', abbrev: 'Ne', testament: 'AT', chapters: 13, usfm: 'NEH' },
  { id: 'EST', name: 'Ester', abbrev: 'Et', testament: 'AT', chapters: 10, usfm: 'EST' },
  { id: 'JOB', name: 'Jó', abbrev: 'Jó', testament: 'AT', chapters: 42, usfm: 'JOB' },
  { id: 'PSA', name: 'Salmos', abbrev: 'Sl', testament: 'AT', chapters: 150, usfm: 'PSA' },
  { id: 'PRO', name: 'Provérbios', abbrev: 'Pv', testament: 'AT', chapters: 31, usfm: 'PRO' },
  { id: 'ECC', name: 'Eclesiastes', abbrev: 'Ec', testament: 'AT', chapters: 12, usfm: 'ECC' },
  { id: 'SNG', name: 'Cânticos', abbrev: 'Ct', testament: 'AT', chapters: 8, usfm: 'SNG' },
  { id: 'ISA', name: 'Isaías', abbrev: 'Is', testament: 'AT', chapters: 66, usfm: 'ISA' },
  { id: 'JER', name: 'Jeremias', abbrev: 'Jr', testament: 'AT', chapters: 52, usfm: 'JER' },
  { id: 'LAM', name: 'Lamentações', abbrev: 'Lm', testament: 'AT', chapters: 5, usfm: 'LAM' },
  { id: 'EZK', name: 'Ezequiel', abbrev: 'Ez', testament: 'AT', chapters: 48, usfm: 'EZK' },
  { id: 'DAN', name: 'Daniel', abbrev: 'Dn', testament: 'AT', chapters: 12, usfm: 'DAN' },
  { id: 'HOS', name: 'Oséias', abbrev: 'Os', testament: 'AT', chapters: 14, usfm: 'HOS' },
  { id: 'JOL', name: 'Joel', abbrev: 'Jl', testament: 'AT', chapters: 3, usfm: 'JOL' },
  { id: 'AMO', name: 'Amós', abbrev: 'Am', testament: 'AT', chapters: 9, usfm: 'AMO' },
  { id: 'OBA', name: 'Obadias', abbrev: 'Ob', testament: 'AT', chapters: 1, usfm: 'OBA' },
  { id: 'JON', name: 'Jonas', abbrev: 'Jn', testament: 'AT', chapters: 4, usfm: 'JON' },
  { id: 'MIC', name: 'Miquéias', abbrev: 'Mq', testament: 'AT', chapters: 7, usfm: 'MIC' },
  { id: 'NAM', name: 'Naum', abbrev: 'Na', testament: 'AT', chapters: 3, usfm: 'NAM' },
  { id: 'HAB', name: 'Habacuque', abbrev: 'Hc', testament: 'AT', chapters: 3, usfm: 'HAB' },
  { id: 'ZEP', name: 'Sofonias', abbrev: 'Sf', testament: 'AT', chapters: 3, usfm: 'ZEP' },
  { id: 'HAG', name: 'Ageu', abbrev: 'Ag', testament: 'AT', chapters: 2, usfm: 'HAG' },
  { id: 'ZEC', name: 'Zacarias', abbrev: 'Zc', testament: 'AT', chapters: 14, usfm: 'ZEC' },
  { id: 'MAL', name: 'Malaquias', abbrev: 'Ml', testament: 'AT', chapters: 4, usfm: 'MAL' },

  // Novo Testamento (27 livros)
  { id: 'MAT', name: 'Mateus', abbrev: 'Mt', testament: 'NT', chapters: 28, usfm: 'MAT' },
  { id: 'MRK', name: 'Marcos', abbrev: 'Mc', testament: 'NT', chapters: 16, usfm: 'MRK' },
  { id: 'LUK', name: 'Lucas', abbrev: 'Lc', testament: 'NT', chapters: 24, usfm: 'LUK' },
  { id: 'JHN', name: 'João', abbrev: 'Jo', testament: 'NT', chapters: 21, usfm: 'JHN' },
  { id: 'ACT', name: 'Atos', abbrev: 'At', testament: 'NT', chapters: 28, usfm: 'ACT' },
  { id: 'ROM', name: 'Romanos', abbrev: 'Rm', testament: 'NT', chapters: 16, usfm: 'ROM' },
  { id: '1CO', name: '1 Coríntios', abbrev: '1Co', testament: 'NT', chapters: 16, usfm: '1CO' },
  { id: '2CO', name: '2 Coríntios', abbrev: '2Co', testament: 'NT', chapters: 13, usfm: '2CO' },
  { id: 'GAL', name: 'Gálatas', abbrev: 'Gl', testament: 'NT', chapters: 6, usfm: 'GAL' },
  { id: 'EPH', name: 'Efésios', abbrev: 'Ef', testament: 'NT', chapters: 6, usfm: 'EPH' },
  { id: 'PHP', name: 'Filipenses', abbrev: 'Fp', testament: 'NT', chapters: 4, usfm: 'PHP' },
  { id: 'COL', name: 'Colossenses', abbrev: 'Cl', testament: 'NT', chapters: 4, usfm: 'COL' },
  { id: '1TH', name: '1 Tessalonicenses', abbrev: '1Ts', testament: 'NT', chapters: 5, usfm: '1TH' },
  { id: '2TH', name: '2 Tessalonicenses', abbrev: '2Ts', testament: 'NT', chapters: 3, usfm: '2TH' },
  { id: '1TI', name: '1 Timóteo', abbrev: '1Tm', testament: 'NT', chapters: 6, usfm: '1TI' },
  { id: '2TI', name: '2 Timóteo', abbrev: '2Tm', testament: 'NT', chapters: 4, usfm: '2TI' },
  { id: 'TIT', name: 'Tito', abbrev: 'Tt', testament: 'NT', chapters: 3, usfm: 'TIT' },
  { id: 'PHM', name: 'Filemom', abbrev: 'Fm', testament: 'NT', chapters: 1, usfm: 'PHM' },
  { id: 'HEB', name: 'Hebreus', abbrev: 'Hb', testament: 'NT', chapters: 13, usfm: 'HEB' },
  { id: 'JAS', name: 'Tiago', abbrev: 'Tg', testament: 'NT', chapters: 5, usfm: 'JAS' },
  { id: '1PE', name: '1 Pedro', abbrev: '1Pe', testament: 'NT', chapters: 5, usfm: '1PE' },
  { id: '2PE', name: '2 Pedro', abbrev: '2Pe', testament: 'NT', chapters: 3, usfm: '2PE' },
  { id: '1JN', name: '1 João', abbrev: '1Jo', testament: 'NT', chapters: 5, usfm: '1JN' },
  { id: '2JN', name: '2 João', abbrev: '2Jo', testament: 'NT', chapters: 1, usfm: '2JN' },
  { id: '3JN', name: '3 João', abbrev: '3Jo', testament: 'NT', chapters: 1, usfm: '3JN' },
  { id: 'JUD', name: 'Judas', abbrev: 'Jd', testament: 'NT', chapters: 1, usfm: 'JUD' },
  { id: 'REV', name: 'Apocalipse', abbrev: 'Ap', testament: 'NT', chapters: 22, usfm: 'REV' },
];

export const LUTHERAN_CURATED_PASSAGES: BibleVerse[] = [
  // Solas da Reforma
  {
    book: 'Romanos',
    bookId: 'ROM',
    chapter: 1,
    verse: '16-17',
    text: 'Pois não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê, primeiro do judeu e também do grego. Porque no evangelho é revelada a justiça de Deus, uma justiça que do princípio ao fim é pela fé, como está escrito: "O justo viverá pela fé".',
    theme: 'Sola Fide (Somente a Fé)',
    lutheranNote: 'Texto fundamental da descoberta reformadora de Martinho Lutero sobre a justificação pela fé somente.',
  },
  {
    book: 'Efésios',
    bookId: 'EPH',
    chapter: 2,
    verse: '8-9',
    text: 'Pois pela graça sois salvos, mediante a fé; e isto não vem de vós, é dom de Deus; não de obras, para que ninguém se glorie.',
    theme: 'Sola Gratia (Somente a Graça)',
    lutheranNote: 'Pilar luterano da salvação como dádiva gratuita de Deus através de Cristo, sem mérito humano.',
  },
  {
    book: 'João',
    bookId: 'JHN',
    chapter: 1,
    verse: '1-5',
    text: 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus. Ele estava no princípio com Deus. Todas as coisas foram feitas por meio dele, e sem ele nada do que foi feito se fez. A vida estava nele e a vida era a luz dos homens. A luz resplandece nas trevas, e as trevas não a derrotaram.',
    theme: 'Cristo, o Verbo Eterno',
    lutheranNote: 'A divindade eterna de Jesus Cristo e a encarnação de Deus na história humana.',
  },
  {
    book: 'João',
    bookId: 'JHN',
    chapter: 1,
    verse: '14',
    text: 'E o Verbo se fez carne e habitou entre nós, cheio de graça e de verdade, e vimos a sua glória, glória como do unigênito do Pai.',
    theme: 'A Encarnação do Salvador',
    lutheranNote: 'O cerne do Natal e da confissão luterana da união das duas naturezas em Cristo.',
  },
  {
    book: 'João',
    bookId: 'JHN',
    chapter: 3,
    verse: '16',
    text: 'Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna.',
    theme: 'O Amor Redentor de Deus',
    lutheranNote: 'O "Evangelho em miniatura": o coração das Escrituras Sagradas.',
  },
  {
    book: 'João',
    bookId: 'JHN',
    chapter: 14,
    verse: '6',
    text: 'Respondeu Jesus: "Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim."',
    theme: 'Solus Christus (Somente Cristo)',
    lutheranNote: 'Cristo é o único Mediador entre Deus e os seres humanos.',
  },
  {
    book: 'Romanos',
    bookId: 'ROM',
    chapter: 3,
    verse: '23-24',
    text: 'Pois todos pecaram e estão destituídos da glória de Deus, sendo justificados gratuitamente por sua graça, por meio da redenção que há em Cristo Jesus.',
    theme: 'Justificação Gratuita',
    lutheranNote: 'A doutrina central sobre a qual a Igreja Luterana se mantém de pé ou cai.',
  },
  {
    book: 'Romanos',
    bookId: 'ROM',
    chapter: 5,
    verse: '1-2',
    text: 'Tendo sido, pois, justificados pela fé, temos paz com Deus, por nosso Senhor Jesus Cristo, por meio de quem obtivemos acesso pela fé a esta graça na qual agora estamos firmes; e nos gloriamos na esperança da glória de Deus.',
    theme: 'Paz com Deus pela Fé',
    lutheranNote: 'A consciência apaziguada pelo perdão conquistado na Cruz do Calvário.',
  },
  {
    book: 'Romanos',
    bookId: 'ROM',
    chapter: 8,
    verse: '28',
    text: 'Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.',
    theme: 'Providência e Cuidado Divino',
    lutheranNote: 'O conforto inabalável do cristão em meio às tribulações e cruzes da vida presente.',
  },
  {
    book: 'Romanos',
    bookId: 'ROM',
    chapter: 8,
    verse: '38-39',
    text: 'Pois estou convencido de que nem morte nem vida, nem anjos nem demônios, nem o presente nem o futuro, nem quaisquer poderes, nem altura nem profundidade, nem qualquer outra coisa na criação será capaz de nos separar do amor de Deus que está em Cristo Jesus, nosso Senhor.',
    theme: 'Segurança Eterna em Cristo',
    lutheranNote: 'A vitória cabal e inseparável do cristão guardado pelo amor de Deus.',
  },
  {
    book: 'Salmos',
    bookId: 'PSA',
    chapter: 23,
    verse: '1-6',
    text: 'O Senhor é o meu pastor; de nada terei falta. Em verdes pastagens faz-me repousar e conduz-me a águas tranquilas; restaura-me o vigor. Guia-me nas veredas da justiça por amor do seu nome. Mesmo quando eu andar por um vale de trevas e morte, não temerei perigo algum, pois tu estás comigo; a tua vara e o teu cajado me protegem. Preparas um banquete para mim à vista dos meus inimigos. Tu unges a minha cabeça com óleo, e o meu cálice transborda. Sei que a bondade e a fidelidade me acompanharão todos os dias da minha vida, e voltarei à casa do Senhor enquanto eu viver.',
    theme: 'O Bom Pastor',
    lutheranNote: 'O Salmo da confiança filial na condução graciosa de Deus em todos os momentos.',
  },
  {
    book: 'Salmos',
    bookId: 'PSA',
    chapter: 46,
    verse: '1-3',
    text: 'Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade. Por isso não temeremos, ainda que a terra trema e os montes afundem no coração do mar, ainda que estrondem as suas águas turbulentas e os montes se sacudam com a sua fúria.',
    theme: 'Castelo Forte é Nosso Deus',
    lutheranNote: 'Inspiração do hino-símbolo da Reforma Luterana composto por Martinho Lutero ("Ein feste Burg ist unser Gott").',
  },
  {
    book: 'Salmos',
    bookId: 'PSA',
    chapter: 91,
    verse: '1-2',
    text: 'Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso pode dizer ao Senhor: "Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio."',
    theme: 'Proteção Divina',
    lutheranNote: 'O refúgio seguro debaixo das asas da misericórdia de Deus.',
  },
  {
    book: 'Salmos',
    bookId: 'PSA',
    chapter: 121,
    verse: '1-2',
    text: 'Levanto os meus olhos para os montes e pergunto: De onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.',
    theme: 'O Socorro que vem do Senhor',
    lutheranNote: 'A oração de peregrinação do povo de Deus confiando no Criador.',
  },
  {
    book: 'Mateus',
    bookId: 'MAT',
    chapter: 6,
    verse: '9-13',
    text: 'Vocês, orem assim: "Pai nosso, que estás nos céus! Santificado seja o teu nome. Venha o teu Reino; seja feita a tua vontade, assim na terra como no céu. Dá-nos hoje o nosso pão de cada dia. Perdoa as nossas dívidas, assim como perdoamos aos nossos devedores. E não nos deixes cair em tentação, mas livra-nos do mal, porque teu é o Reino, o poder e a glória para sempre. Amém."',
    theme: 'A Oração do Senhor (Pai Nosso)',
    lutheranNote: 'Explicado com profundidade pedagógica e pastoral no Catecismo Menor de Lutero.',
  },
  {
    book: 'Mateus',
    bookId: 'MAT',
    chapter: 28,
    verse: '18-20',
    text: 'Então, Jesus aproximou-se deles e disse: "Foi-me dada toda a autoridade no céu e na terra. Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo, ensinando-os a obedecer a tudo o que eu lhes ordenei. E eu estarei sempre com vocês, até o fim dos tempos."',
    theme: 'A Grande Comissão e o Santo Batismo',
    lutheranNote: 'Fundamento evangélico da missão da Igreja e da administração do Santo Batismo com a promessa da presença de Cristo.',
  },
  {
    book: '1 Coríntios',
    bookId: '1CO',
    chapter: 11,
    verse: '23-26',
    text: 'Pois recebi do Senhor o que também lhes entreguei: Que o Senhor Jesus, na noite em que foi traído, tomou o pão e, tendo dado graças, partiu-o e disse: "Isto é o meu corpo, que é dado em favor de vocês; façam isto em memória de mim." Da mesma forma, depois da ceia ele tomou o cálice e disse: "Este cálice é a nova aliança no meu sangue; façam isto, sempre que o beberem, em memória de mim." Porque, sempre que comerem deste pão e beberem deste cálice, vocês anunciam a morte do Senhor até que ele venha.',
    theme: 'O Sacramento do Altar (Santa Ceia)',
    lutheranNote: 'A doutrina da Presença Real de Cristo no sacramento: o verdadeiro corpo e sangue sob o pão e o vinho para o perdão dos pecados.',
  },
  {
    book: '1 Coríntios',
    bookId: '1CO',
    chapter: 13,
    verse: '4-7',
    text: 'O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. Não maltrata, não procura seus interesses, não se ira facilmente, não guarda rancor. O amor não se alegra com a injustiça, mas se alegra com a verdade. Tudo sofre, tudo crê, tudo espera, tudo suporta.',
    theme: 'O Amor Cristão (Ágape)',
    lutheranNote: 'O fruto e o transbordamento da fé viva na vocação diária junto ao próximo.',
  },
  {
    book: '2 Timóteo',
    bookId: '2TI',
    chapter: 3,
    verse: '16-17',
    text: 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça, para que o homem de Deus seja apto e plenamente preparado para toda boa obra.',
    theme: 'Sola Scriptura (Somente as Escrituras)',
    lutheranNote: 'A Bíblia Sagrada como a única norma e regra para a fé e a vida cristã.',
  },
  {
    book: 'Gálatas',
    bookId: 'GAL',
    chapter: 2,
    verse: '20',
    text: 'Fui crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo-a pela fé no filho de Deus, que me amou e se entregou por mim.',
    theme: 'Vida em Cristo',
    lutheranNote: 'A nova identidade batismal de quem foi enxertado na morte e ressurreição de Cristo.',
  },
  {
    book: 'Gálatas',
    bookId: 'GAL',
    chapter: 5,
    verse: '22-23',
    text: 'Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. Contra estas coisas não há lei.',
    theme: 'O Fruto do Espírito Santo',
    lutheranNote: 'A santificação genuína operada pelo Espírito Santo nos crentes pela Palavra e Sacramentos.',
  },
  {
    book: 'Filipenses',
    bookId: 'PHP',
    chapter: 4,
    verse: '6-7',
    text: 'Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus. E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.',
    theme: 'A Paz de Deus que Excede o Entendimento',
    lutheranNote: 'O convite pastoral ao descanso e oração confiante na fidelidade divina.',
  },
  {
    book: 'Filipenses',
    bookId: 'PHP',
    chapter: 4,
    verse: '13',
    text: 'Tudo posso naquele que me fortalece.',
    theme: 'Força em Cristo',
    lutheranNote: 'O contentamento e a capacitação espiritual que o Senhor concede em todas as circunstâncias.',
  },
  {
    book: 'Tiago',
    bookId: 'JAS',
    chapter: 1,
    verse: '22',
    text: 'Sejam praticantes da palavra, e não apenas ouvintes, enganando-se a si mesmos.',
    theme: 'A Fé Viva em Ação',
    lutheranNote: 'A fé verdadeira nunca permanece inerte; ela se expressa em serviço ao próximo.',
  },
  {
    book: '1 Pedro',
    bookId: '1PE',
    chapter: 5,
    verse: '7',
    text: 'Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.',
    theme: 'Cuidado Paterno de Deus',
    lutheranNote: 'A certeza reconfortante de que o Senhor zela por cada um dos seus filhos.',
  },
  {
    book: '1 João',
    bookId: '1JN',
    chapter: 1,
    verse: '8-9',
    text: 'Se afirmarmos que estamos sem pecado, enganamos a nós mesmos, e a verdade não está em nós. Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça.',
    theme: 'Confissão e Absolvição',
    lutheranNote: 'Uso litúrgico na abertura do Culto Luterano e no rito da confissão de pecados.',
  },
  {
    book: 'Gênesis',
    bookId: 'GEN',
    chapter: 1,
    verse: '1-3',
    text: 'No princípio Deus criou os céus e a terra. Era a terra sem forma e vazia; trevas cobriam a face do abismo, e o Espírito de Deus se movia sobre a face das águas. Disse Deus: "Haja luz!", e houve luz.',
    theme: 'A Criação de Todas as Coisas',
    lutheranNote: 'Primeiro Artigo do Credo Apostólico: "Creio em Deus Pai todo-poderoso, Criador do céu e da terra".',
  },
  {
    book: 'Isaías',
    bookId: 'ISA',
    chapter: 9,
    verse: '6',
    text: 'Porque um menino nos nasceu, um filho nos foi dado, e o governo está sobre os seus ombros. E ele será chamado Maravilhoso Conselheiro, Deus Poderoso, Pai Eterno, Príncipe da Paz.',
    theme: 'A Promessa Messiânica',
    lutheranNote: 'A profecia central do Advento e Natal sobre o Messias encarnado.',
  },
  {
    book: 'Isaías',
    bookId: 'ISA',
    chapter: 40,
    verse: '31',
    text: 'Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.',
    theme: 'Esperança Renovada no Senhor',
    lutheranNote: 'A renovação das forças espirituais na Palavra e na promessa de Deus.',
  },
  {
    book: 'Isaías',
    bookId: 'ISA',
    chapter: 53,
    verse: '4-5',
    text: 'Certamente ele tomou sobre si as nossas enfermidades e sobre si levou as nossas doenças; contudo nós o consideramos castigado por Deus, por Deus atingido e afligido. Mas ele foi transpassado por causa das nossas transgressões, foi esmagado por causa de nossas iniquidades; o castigo que nos trouxe a paz estava sobre ele, e pelas suas feridas fomos curados.',
    theme: 'O Servo Sofredor (A Cruz)',
    lutheranNote: 'A Teologia da Cruz (Theologia Crucis) e o sacrifício vicário de Jesus por todos nós.',
  },
  {
    book: 'Provérbios',
    bookId: 'PRO',
    chapter: 3,
    verse: '5-6',
    text: 'Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.',
    theme: 'Confiança e Sabedoria',
    lutheranNote: 'A sabedoria piedosa de colocar os passos diários sob o conselho do Altíssimo.',
  },
  {
    book: 'Josué',
    bookId: 'JOS',
    chapter: 1,
    verse: '9',
    text: 'Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.',
    theme: 'Coragem na Vocação',
    lutheranNote: 'A certeza da presença de Deus nas responsabilidades e desafios do cristão.',
  },
  {
    book: 'Jeremias',
    bookId: 'JER',
    chapter: 29,
    verse: '11',
    text: '"Porque sou eu que conheço os planos que tenho para vocês", diz o Senhor, "planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro."',
    theme: 'Planos de Paz e Futuro',
    lutheranNote: 'A bondade soberana de Deus guiando o Seu povo mesmo no cativeiro e tribulação.',
  },
];
